###

## load R data generated by phylo-muscle-phangorn.R
load('phylo-ggtree.RData')

## library
library(ggplot2)
library(ggtree)

## ggtree
ggtree(treeUPGMA)+geom_tiplab()
ggtree(treeNJ)+geom_tiplab()

gt=read.tree('NANOG-NJ-MEGA.newick')
ggtree(gt)
ggtree(gt)+geom_tiplab()
ggtree(gt,layout='circular')+geom_tiplab()+geom_treescale()

ggtree(fitGTR$tree)+geom_tiplab()

# add some tip labels and a title
ggtree(tree, right = TRUE) + ggtitle("Test Tree") + geom_tiplab(size = 2)

# right aligned labels
ggtree(tree, right = TRUE) + ggtitle("Test Tree") + geom_tiplab(size = 2, align=TRUE, linesize=.25)  + geom_treescale(x=0.05, y=0, offset=2, fontsize = 3) + ggplot2::xlim(0, 0.3)

# add bootstrap value

p <- ggtree(tree, right = TRUE) + ggtitle("Test Tree") + geom_tiplab(size = 2, align=TRUE, linesize=.25)  + geom_treescale(x=0.05, y=0, offset=2, fontsize = 3) + ggplot2::xlim(0, 0.3)

d <- p$data
d <- d[!d$isTip,]
d$label <- as.numeric(d$label)
d <- d[d$label > 65,]
p <- p + geom_text(data=d, aes(label=label), size=3, hjust = 1.25, vjust = -0.4)
plot(p)







## Export plots to PPT
library(export)
t=gsub(":","-",gsub(" ","-",as.character(Sys.time())))
graph2ppt(file=paste0("Rplot-",t,".pptx"))

